### ISSUE TITLE
AntPagination only one page, button is clickable

### ISSUE THREAD

**Issue by beyer-johannes** [antify/ui-module#9]
If the pages property is 1, the button 1 is clickable.
This click whould emit a new request and table load which is a bad ux and a performance issue.

General, the current page should not be clickable:

![image](https://github.com/antify/ui-module/assets/18086044/cbea2d94-03a6-47af-bec3-37db4f2586f4)

**Comment by NaXiDaXi** [comment]
Can this issue close? bug is fixed.
